# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: silenzio
  CLOUD_SQL_PASSWORD: YOUR-DB-PASSWORD
  CLOUD_SQL_DATABASE_NAME: typing_database
  CLOUD_SQL_CONNECTION_NAME: resonant-truth-282112:europe-west3:typing
# [END gae_python37_cloudsql_config]
